from typing import Annotated, Optional, List

from pydantic import Field, BaseModel, field_serializer

from app.agent.experience import ExperienceEntity, Timeline, WorkType
from app.agent.explore_experiences_agent_director import DiveInPhase
from app.vector_search.esco_entities import SkillEntity


# ------------------------- Utility Functions -------------------------

def convert_skill_entities_to_skills_response(skills_entities: list[SkillEntity | tuple[int, SkillEntity]]) -> list["SkillResponse"]:
    """
    Extracts SkillEntity objects from a list of SkillEntity or tuple[int, SkillEntity]
    in an ordered format each with orderIndex.

    For tuples, the first element is the order index, which will be used as the orderIndex.
    """

    if not skills_entities or len(skills_entities) == 0:
        return []

    if isinstance(skills_entities[0], tuple):
        return [
            SkillResponse.from_skill_entity(skill_entity=skill_entity, order_index=idx)
            for idx, skill_entity in sorted(skills_entities, key=lambda x: x[0])
        ]
    else:
        # unexplored-experiences:
        # they don't have any skills, it is going to be an empty list.
        return [
            SkillResponse.from_skill_entity(skill_entity=skill_entity, order_index=0)
            for idx, skill_entity in enumerate(skills_entities)
        ]

# ------------------------- Response Models -------------------------


class SkillResponse(BaseModel):
    """
    A skill entity for the user.

    It excludes the fields that are not relevant to the user.
    """

    UUID: str
    preferredLabel: str
    altLabels: list[str]
    description: str
    orderIndex: int

    class Config:
        extra = "forbid"

    @staticmethod
    def from_skill_entity(skill_entity: SkillEntity, order_index: int) -> "SkillResponse":
        """
        Build a SkillResponse from a SkillEntity.
        """

        return SkillResponse(
            UUID=skill_entity.UUID,
            preferredLabel=skill_entity.preferredLabel,
            altLabels=skill_entity.altLabels,
            description=skill_entity.description,
            orderIndex=order_index,
        )


class ExperienceResponse(BaseModel):
    """
    Response model for an experience.
    Inherits all fields from BaseExperienceEntity and adds exploration_phase and top_skills.
    """

    UUID: str

    experience_title: Optional[str] = None
    """
    Title of the experience as the user refers to it (e.g. "Crew Member")
    """

    company: Optional[str] = None
    """
    Company name (e.g. "at McDonald's")
    """

    # location: Optional[str] = None
    # """
    # Location of the experience (e.g. "Cape Town, South Africa")
    # """

    timeline: Optional[Timeline] = None
    """
    Start and end date of the experience
    """

    work_type: Optional[WorkType] = None
    """
    Type of work (e.g. "waged-employee")
    """

    summary: Optional[str] = None
    """
    A summary of the experience, generated by the ExperienceSummarizer.
    This is a human-readable string that summarizes the experience.
    """

    exploration_phase: Annotated[str, Field(
        description=f"The current sub-phase of the experience exploration. Allowed values: {[e.name for e in DiveInPhase]}",
        examples=[e.name for e in DiveInPhase],
    )] = DiveInPhase.NOT_STARTED.name
    """
    The current sub-phase of the experience exploration.
    """

    top_skills: List[SkillResponse]
    """
    List of skills identified as relevant to the experience.
    """

    remaining_skills: List[SkillResponse]
    """
    List of skills that were not identified as top skills but are still relevant to the experience.
    """

    # use a field serializer to serialize the work_type
    # we use the name of the Enum instead of the value because that makes the code less brittle
    @field_serializer("work_type")
    def serialize_work_type(self, work_type: WorkType, _info):
        if work_type is not None:
            return work_type.name
        return None

    class Config:
        """
        Doc config
        """
        extra = "forbid"

    @staticmethod
    def from_experience_entity(experience_entity: ExperienceEntity, dive_in_phase: DiveInPhase) -> "ExperienceResponse":
        """
        Converts an ExperienceEntity object into an Experience Response object by mapping its
        attributes and creating any necessary nested objects.
        """

        return ExperienceResponse(
            UUID=experience_entity.uuid,
            experience_title=experience_entity.experience_title,
            company=experience_entity.company,
            # location=experience_entity.location,
            timeline=experience_entity.timeline,
            work_type=experience_entity.work_type,
            top_skills=convert_skill_entities_to_skills_response(experience_entity.top_skills),
            remaining_skills=convert_skill_entities_to_skills_response(experience_entity.remaining_skills),
            summary=experience_entity.summary,
            exploration_phase=dive_in_phase.name,
        )


# ------------------------- Request Models -------------------------

# Field length limits (keep in sync with frontend)
EXPERIENCE_TITLE_MAX_LENGTH = 100
COMPANY_MAX_LENGTH = 100
LOCATION_MAX_LENGTH = 100
SUMMARY_MAX_LENGTH = 1000
UUID_MAX_LENGTH = 36
SKILL_LABEL_MAX_LENGTH = 100
TIMELINE_MAX_LENGTH = 30


class SkillUpdate(BaseModel):
    """
    A skill to be updated in an experience.
    """

    UUID: Annotated[
        str,
        Field(
            description="Unique identifier for the skill.",
            max_length=UUID_MAX_LENGTH
        )]

    preferredLabel: Annotated[
        str,
        Field(
            description="The preferred label for the skill.",
            max_length=SKILL_LABEL_MAX_LENGTH
        )]

    class Config:
        extra = "forbid"


class TimelineUpdate(Timeline):
    start: Optional[str] = Field(
        default=None,
        description="The start date of the experience. If omitted, not updated. If null, cleared.",
        examples=["A long time ago", "2020", "2020-01", "2020-01-01"],
        max_length=TIMELINE_MAX_LENGTH,
    )

    end: Optional[str] = Field(
        default=None,
        description="The end date of the experience. If omitted, not updated. If null, cleared.",
        examples=["Present", "2021", "2021-12", "2021-12-31", "Present", "A long time ago"],
        max_length=TIMELINE_MAX_LENGTH,
    )


class UpdateExperienceRequest(BaseModel):
    """
    Request model for updating an experience.

    - If a field is omitted, it will not be updated.
    - If a field is present with a null value, it will be cleared (set to None or empty).
    - If a field is present with a value, it will be updated to that value.

    Special handling for top_skills:
    - If omitted: top_skills will not be updated.
    - If present as null: all skills will be removed (set to empty list).
    - If present as an empty list: all skills will be removed (set to empty list).
    - If present as a list of SkillUpdate: will update to that list.
    """
    experience_title: Optional[str] = Field(
        default=None,
        description="The title of the experience. If omitted, not updated. If null, cleared.",
        examples=["Crew Member"],
        max_length=EXPERIENCE_TITLE_MAX_LENGTH
    )
    timeline: Optional[TimelineUpdate] = Field(
        default=None,
        description="The timeline of the experience (start/end). If omitted, not updated. If null, cleared.",
    )
    company: Optional[str] = Field(
        default=None,
        description="The company name. If omitted, not updated. If null, cleared.",
        examples=["McDonald's"],
        max_length=COMPANY_MAX_LENGTH
    )
    # location: Optional[str] = Field(
    #     default=None,
    #     description="The location of the experience. If omitted, not updated. If null, cleared.",
    #     examples=["Cape Town, South Africa"],
    #     max_length=LOCATION_MAX_LENGTH
    # )

    # Use the type as `str` to allow the API user to send the keys.
    # By default, Pydantic will convert the enum to its value.
    # And the client is expected to send the keys instead of the values.
    work_type: Optional[str] = Field(
        default=None,
        description="The type of work. "
                    "If omitted, not updated. If null, cleared. "
                    "If an invalid value is provided, null will be saved.",
        examples=[WorkType.FORMAL_SECTOR_WAGED_EMPLOYMENT.name],
        max_length=max(len(e.name) for e in WorkType),
        json_schema_extra={"enum": [e.name for e in WorkType] + [None]}
    )
    summary: Optional[str] = Field(
        default=None,
        description="A summary of the experience. If omitted, not updated. If null, cleared.",
        examples=["Worked as a crew member at McDonald's."],
        max_length=SUMMARY_MAX_LENGTH
    )
    top_skills: Optional[List[SkillUpdate]] = Field(
        default=None,
        description="List of skills to update. If omitted, not updated. If null or empty list, all skills will be removed.",
        examples=[[{"UUID": "skill-uuid-1", "preferredLabel": "Customer Service"}]]
    )

    class Config:
        extra = "forbid"
