# openapi2-functions.yaml
swagger: '2.0'
info:
  title: Compass API Gateway Config
  description: Compass API Gateway Config
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: "{1}"
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/{0}"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "{0}"
paths:
  insert-paths-here
