from typing import Awaitable
import pytest

from app.conversations.reactions.types import ReactionKind, DislikeReason
from app.metrics.types import UserAccountCreatedEvent
from common_libs.time_utilities import mongo_date_to_datetime, truncate_microseconds

from app.metrics.repository import CompassMetricRepository

from app.app_config import ApplicationConfig

@pytest.fixture(scope="function")
async def get_metrics_repository(in_memory_metrics_database) -> CompassMetricRepository:
    metrics_db = await in_memory_metrics_database
    return CompassMetricRepository(db=metrics_db)


def get_user_account_created_event():
    return UserAccountCreatedEvent(
        user_id="123",
    )

class TestRecordEvent:
    @pytest.mark.asyncio
    @pytest.mark.parametrize(
        "given_event_generator",
        [
            get_user_account_created_event,
        ],
        ids=[
            "user_account_created",
        ]
    )
    async def test_record_single_event_success(
            self,
            get_metrics_repository: Awaitable[CompassMetricRepository],
            given_event_generator,
            setup_application_config: ApplicationConfig
    ):
        # GIVEN an event of a specific type
        repository = await get_metrics_repository
        given_event = given_event_generator()

        # WHEN the event is recorded
        # Guard: ensure no events in the database
        assert await repository.collection.count_documents({}) == 0
        await repository.record_event([given_event])

        # THEN the event is recorded in the database
        assert await repository.collection.count_documents({}) == 1

        # AND the event data matches what we expect
        actual_stored_event = await repository.collection.find_one({})

        # Compare all fields from the original event
        # Remove the id field from the comparison since it's generated by MongoDB
        given_event_dict = given_event.model_dump()
        given_event_dict.pop("_id", None)
        for field, value in given_event_dict.items():
            if field == "kind" and isinstance(value, ReactionKind):
                # Special case for reaction kind which is stored as string
                assert actual_stored_event[field] == value.name
            elif field == "reasons" and value and isinstance(value[0], DislikeReason):
                # Special case for empty reasons list in stored event
                assert actual_stored_event[field] == []
            elif field == "timestamp":
                # Special case for timestamp which needs to be converted from MongoDB format
                assert truncate_microseconds(mongo_date_to_datetime(actual_stored_event[field])) == truncate_microseconds(value)
            else:
                assert actual_stored_event[field] == value
        
    @pytest.mark.asyncio
    async def test_record_multiple_user_account_creation_events_success(
            self,
            get_metrics_repository: Awaitable[CompassMetricRepository],
            setup_application_config: ApplicationConfig
    ):
        # GIVEN a list of events
        given_events = [get_user_account_created_event(), get_user_account_created_event()]
        repository = await get_metrics_repository

        # Guard: ensure no events in the database
        assert await repository.collection.count_documents({}) == 0

        # WHEN the events are recorded
        await repository.record_event(given_events)

        # THEN the events are recorded in the database
        assert await repository.collection.count_documents({}) == len(given_events)

        # AND the event data matches what we expect
        actual_stored_events = await repository.collection.find({}).to_list(length=len(given_events))
        for actual_stored_event, expected_event in zip(actual_stored_events, given_events):
            # Remove the id field from the comparison since it's generated by MongoDB
            expected_event_dict = expected_event.model_dump()
            expected_event_dict.pop("_id", None)
            for field, value in expected_event_dict.items():
                if field == "kind" and isinstance(value, ReactionKind):
                    # Special case for reaction kind which is stored as string
                    assert actual_stored_event[field] == value.name
                elif field == "reasons" and value and isinstance(value[0], DislikeReason):
                    # Special case for empty reasons list in stored event
                    assert actual_stored_event[field] == []
                elif field == "timestamp":
                    # Special case for timestamp which needs to be converted from MongoDB format
                    assert truncate_microseconds(mongo_date_to_datetime(actual_stored_event[field])) == truncate_microseconds(value)
                else:
                    assert actual_stored_event[field] == value
            
        
