class Collections:
    USER_PREFERENCES: str = "user_preferences"
    SENSITIVE_PERSONAL_DATA: str = "sensitive_personal_data"
    USER_INVITATIONS: str = "user_invitations"
    AGENT_DIRECTOR_STATE = "agent_director_state"
    WELCOME_AGENT_STATE = "welcome_agent_state"
    EXPLORE_EXPERIENCES_DIRECTOR_STATE = "explore_experiences_director_state"
    CONVERSATION_MEMORY_MANAGER_STATE = "conversation_memory_manager_state"
    COLLECT_EXPERIENCE_STATE = "collect_experience_state"
    SKILLS_EXPLORER_AGENT_STATE = "skills_explorer_agent_state"
    PREFERENCE_ELICITATION_AGENT_STATE = "preference_elicitation_agent_state"
    USER_FEEDBACK = "user_feedback"
    REACTIONS = "reactions"
    COMPASS_METRICS = "metric_events"
    USER_CV_UPLOADS: str = "user_cv_uploads"
