services:
  k6:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./.:/k6s
    entrypoint: ["/bin/bash", "run.sh"]
    network_mode: host
