"""
This module contains the types used for storing sensitive personal data.
"""

from enum import Enum
from typing import Union, Mapping
from datetime import datetime, timezone
from pydantic import BaseModel, Field, field_validator, field_serializer


class SensitivePersonalDataRequirement(Enum):
    """
    Represents the requirement of the sensitive data
    """

    REQUIRED = "REQUIRED"
    NOT_REQUIRED = "NOT_REQUIRED"


class SensitivePersonalDataStatus(Enum):
    """
    Represents the status of the sensitive personal data
    """

    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"


class CreateSensitivePersonalDataRequest(BaseModel):
    """
    Represents the request body for creating sensitive personal data.
    """

    # rsa key id should not exceed 256 characters
    rsa_key_id: str = Field(
        description="The key ID of the RSA key used to encrypt the AES key",
        examples=["key_123"],
        max_length=256
    )
    """
    The key ID of the RSA key used to encrypt the AES key.
    """

    # Max field length is set to 1000 characters for the following reasons:
    # - We use a 256-bit AES key (32 bytes) encrypted with a 4096-bit RSA key.
    # - RSA encryption results in a block size of 512 bytes (4096 bits / 8).
    # - When Base64 encoded, the size becomes approximately 682 bytes ((512 * 4/3) + padding).
    # - Adding up to 4 bytes for Base64 padding gives a total of 686 bytes.
    # - To allow for tolerance and stay within limits, we round up the max length to 1000 characters.
    aes_encryption_key: str = Field(
        description="RSA encrypted AES key used to encrypt/decrypt sensitive user data.",
        examples=["ZGFzZGE="],
        max_length=1000
    )
    """
    The AES key used to encrypt/decrypt the sensitive user data. it is RSA encrypted.
    """

    # Max field size is set to 35,000 characters based on the following calculations:
    # - Assumes encryption of 15 fields, each with keys and values up to 256 characters long, so the sum is 256 * 2
    #   (e.g., "first_name": "foo:, "last_name": "bar", "gender" etc.).
    # - Each character is up to 3 bytes in UTF-8 (worst-case scenario), resulting in 256 * 2 * 3 = 1536 bytes per field.
    # - For 15 fields: 15 * 1536 = 23,040 bytes (JSON structure included).
    # - AES-GCM encryption adds a 16-byte tag and a 12-byte IV to the payload.
    # - Total encrypted payload size: 23,040 bytes + 16 bytes (tag) + 12 bytes (IV) = 23,068 bytes.
    # - Base64 encoding increases the size by ~4/3, resulting in approximately 30,757.3 bytes.
    # - Adding tolerance for overhead, the max size is rounded to 35,000 characters for safety.
    aes_encrypted_data: str = Field(
        description="The Base64-encoded encrypted user-sensitive data combined with IV and authentication tag.",
        examples=["ZGFzZGFkZGFkw=="],
        max_length=35000
    )
    """
    The encrypted sensitive user data, 
    encrypted using the AES encryption key, joined with the IV, and Authentication Tag.
    """

    class Config:
        """
        Pydantic configuration.
        """

        extra = "forbid"


class SensitivePersonalData(BaseModel):
    """
    This class represents sensitive personal data with various cryptographic key attributes.
    It also handles serialization and deserialization of timestamp data to ensure consistent timezone handling.

    It is a schema for the sensitive personal data document in the database.
    """

    user_id: str
    """
    the user id
    """

    rsa_key_id: str
    """
    RSA key id, used to help us know which key was used to encrypt the AES key
    """

    aes_encryption_key: str
    """
    The RSA encrypted AES random key,
    """

    aes_encrypted_data: str
    """
    AES encrypted data
    
    The data consists of three parts:
        - The first part, with a fixed length of 12 bytes (AES-GCM), contains the initialization vector (IV).
            the same number here must be the ones from these lines
            encryptionService.ts
            decrypt_sensitive_personal_data.py
        - The tag which is 16 bytes long. This is the authentication tag generated by the AES-GCM encryption.
        - The third part is the encrypted JSON representation of the user's sensitive data
    """

    created_at: datetime
    """
    the date and time the database entry was created
    """

    # Serialize the creation_time datetime to ensure it's stored as UTC
    @field_serializer("created_at")
    def _serialize_creation_time(self, creation_time: datetime) -> str:
        return creation_time.isoformat()

    # Deserialize the creation_time datetime and ensure it's interpreted as UTC
    @classmethod
    @field_validator("created_at", mode='before')
    def _deserialize_creation_time(cls, value: Union[str, datetime]) -> datetime:
        if isinstance(value, str):
            dt = datetime.fromisoformat(value)
        else:
            dt = value
        return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)

    @staticmethod
    def from_dict(_dict: Mapping[str, any]) -> "SensitivePersonalData":
        """
        Converts a dictionary to a `SensitivePersonalData` object.

        This method extracts fields from a provided dictionary, and initializes a
        `SensitivePersonalData` object with those values.

        :param _dict: A mapping from string keys to corresponding values,
                      representing the attributes of a `SensitivePersonalData` object.

        :return: An instance of `SensitivePersonalData` initialized from the
                 provided dictionary.
        """

        return SensitivePersonalData(
            user_id=str(_dict.get("user_id")),
            aes_encrypted_data=_dict.get("aes_encrypted_data"),
            rsa_key_id=_dict.get("rsa_key_id"),
            aes_encryption_key=_dict.get("aes_encryption_key"),
            created_at=_dict.get("created_at"),
        )

    class Config:
        """
        Pydantic configuration for the SensitivePersonalData class.
        """

        extra = "forbid"
