#!/usr/bin/env python3

import os
import json
import asyncio
import logging
import argparse

from motor.motor_asyncio import AsyncIOMotorClient

from app.invitations.repository import UserInvitationRepository
from app.invitations.types import UserInvitation

logger = logging.getLogger(__name__)


async def main(input_file: str):
    logger.info(f"Setting up invitation codes from the input file: {input_file}")

    # 1. Ensure that the input file exists and is a valid JSON file.
    with open(os.path.join(input_file)) as f:
        given = json.load(f, )

    # 2. Connect to the database
    mongo_uri = os.getenv("INVITATION_CODES_MONGODB_URI")
    if not mongo_uri:
        raise ValueError("The MongoDB URI is not set in the environment variables (INVITATION_CODES_MONGODB_URI)")

    database_name = os.getenv("INVITATION_CODES_DB_NAME")
    if not database_name:
        raise ValueError("The database name is not set in the environment variables (INVITATION_CODES_DB_NAME)")

    # 3. Connect to MongoDB
    client = AsyncIOMotorClient(mongo_uri, tlsAllowInvalidCertificates=True)
    db = client.get_database(database_name)
    repository = UserInvitationRepository(db)

    # 4. Upsert the invitation codes

    # Validate the JSON file contents to match the UserInvitation schema.
    invitation_codes = []
    for item in given:
        invitation_codes.append(UserInvitation(
            **item,
            # ID is not required in the given as it will be generated by MongoDB.
            # I am adding it here to hack Pydantic's schema validation.
            id="",
        ))

    # Upsert the invitation codes
    await repository.upsert_many_invitation_codes(invitation_codes)

    logger.info(f"Successfully saved {len(invitation_codes)} invitation codes to the database.")

    # 5. Close the database connection
    client.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Set up invitation codes from a JSON file")

    parser.add_argument(
        "--input-file",
        type=str,
        required=True,
        help="The path to the JSON file with invitation codes, (absolute or relative to the current working directory)",
    )

    args = parser.parse_args()
    asyncio.run(main(input_file=args.input_file))
