name: Tabiya Compass Unit Tests
on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
      upload-artifacts:
        required: true
        type: boolean
        description: 'Whether to upload deployable the artifacts or not'
      realm-name:
        required: true
        type: string

    outputs:
      version-info:
        description: 'The backend built version info'
        value: ${{ jobs.build-and-upload-artifacts.outputs.version-info }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-0
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
      - name: Load cached Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}
      - name: Install dependencies
        shell: bash
        run: |
          poetry lock --no-update --no-interaction
          poetry install --no-interaction
        working-directory: backend
      - name: Linting Bandit
        shell: bash
        run: poetry run bandit -c bandit.yaml -r .
        working-directory: backend
      - name: Linting Pylint
        shell: bash
        # Do not fail the build if there are linting errors (--exit-zero)
        # Once we have fixed all the linting errors, we can remove this flag
        run: poetry run pylint --exit-zero --recursive=y .
        working-directory: backend
      - name: Setup google-cloud-auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json:
            ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      - name: Run unit tests
        shell: bash
        run: poetry run pytest -m 'not (evaluation_test or smoke_test)'
        working-directory: backend
        env:
          TAXONOMY_MONGODB_URI: foo
          TAXONOMY_DATABASE_NAME: foo
          TAXONOMY_MODEL_ID: foo
          APPLICATION_MONGODB_URI: foo
          APPLICATION_DATABASE_NAME: foo
          USERDATA_MONGODB_URI: foo
          USERDATA_DATABASE_NAME: foo
          TARGET_ENVIRONMENT: foo
          VERTEX_API_REGION: bar
          BACKEND_URL: http://foo.bar
          FRONTEND_URL: http://foo.bar
          ENABLE_SENTRY: "False" # Disable Sentry for unit tests on the pipeline, since tests break with sentry init

  build-and-upload-artifacts:
    needs: unit-test
    runs-on: ubuntu-latest
    if: ${{ inputs.upload-artifacts }}
    environment: ${{ inputs.target-environment }}
    outputs:
      version-info: ${{ steps.setVersionInfo.outputs.version-info }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: authenticate to google cloud
        id: auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json:
            ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - name: set docker region
        run: gcloud auth configure-docker ${{ vars.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Set Version Info
        id: setVersionInfo
        # see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        # for multiline strings
        run: |
          ./pipeline/setVersionInfo.sh ./backend/app/version/version.json
          cat ./backend/app/version/version.json
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "version-info<<$EOF" >> "$GITHUB_OUTPUT"
          echo "$(cat ./backend/app/version/version.json)" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - name: build and push image
        uses: docker/build-push-action@v6
        env:
          REPOSITORY_URL: ${{ vars.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev/${{ secrets.GCP_ROOT_PROJECT_ID }}/${{ inputs.realm-name }}-docker-repository/backend
        with:
          context: backend
          push: true
          tags: ${{ env.REPOSITORY_URL }}:latest,${{ env.REPOSITORY_URL }}:${{ github.sha }}
