name: Tabiya Compass Frontend Deploy
on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
      backend-url:
        required: true
        type: string
      identity_platform_client_api_key:
        required: true
        type: string
      identity_platform_client_firebase_auth_domain:
        required: true
        type: string
      sensitive-data-encryption-key:
        required: true
        type: string
      sensitive-data-encryption-key-id:
        required: true
        type: string
      version:
        description: 'which version to deploy, it may be a hash or a tag or a version'
        required: true
        type: string
      realm-name:
        required: true
        type: string
    outputs:
      frontend-url:
        description: 'The bucket frontend url'
        value: ${{ jobs.deploy.outputs.frontend-url }}

jobs:
  deploy:
    name: deploy-frontend
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    outputs:
      frontend-url: ${{ steps.pulumi.outputs.new_ui_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: authenticate to google cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          project_id: ${{ secrets.GCP_ROOT_PROJECT_ID }}
          credentials_json:
            ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      - name: download frontend build bundle
        run: |
          gcloud artifacts generic download --package=frontend \
            --repository=${{ inputs.realm-name }}-generic-repository \
            --location=${{ vars.ARTIFACT_REGISTRY_REGION }} \
            --destination=./ \
            --project=${{ secrets.GCP_ROOT_PROJECT_ID }} \
            --version=${{ inputs.version }}
          tar -xvf build-v1.0.tar.gz
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install python packages
        run: pip install -r requirements.txt
        working-directory: iac
      - name: Setup google-cloud-auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      - name: Build frontend-new env.js file
        # we are basically creating a js file with the passed env variables
        # that can be executed in the client browser when the js file is loaded
        run: |
          touch frontend-new/build/data/env.js
          echo "window.tabiyaConfig = {" > frontend-new/build/data/env.js
          echo "\"FIREBASE_API_KEY\": btoa(\"${{ inputs.identity_platform_client_api_key }}\")," >> frontend-new/build/data/env.js
          echo "\"FIREBASE_AUTH_DOMAIN\": btoa(\"${{ inputs.identity_platform_client_firebase_auth_domain }}\")," >> frontend-new/build/data/env.js
          echo "\"BACKEND_URL\": btoa(\"${{ inputs.backend-url }}\")," >> frontend-new/build/data/env.js
          echo "\"SENTRY_FRONTEND_DSN\": btoa(\"${{ secrets.SENTRY_FRONTEND_DSN }}\")," >> frontend-new/build/data/env.js
          echo "\"SENTRY_AUTH_TOKEN\": btoa(\"${{ secrets.SENTRY_AUTH_TOKEN }}\")," >> frontend-new/build/data/env.js
          echo "\"SENSITIVE_PERSONAL_DATA_RSA_ENCRYPTION_KEY\": btoa(\`${{ vars.SENSITIVE_PERSONAL_DATA_RSA_ENCRYPTION_KEY }}\`)," >> frontend-new/build/data/env.js
          echo "\"SENSITIVE_PERSONAL_DATA_RSA_ENCRYPTION_KEY_ID\": btoa(\"${{ vars.SENSITIVE_PERSONAL_DATA_RSA_ENCRYPTION_KEY_ID }}\")," >> frontend-new/build/data/env.js
          echo "};" >> frontend-new/build/data/env.js
          cat frontend-new/build/data/env.js
      - name: Deploy both frontends
        id: pulumi
        uses: pulumi/actions@v5
        with:
          work-dir: iac/frontend
          command: up
          stack-name: tabiya-tech/compass-frontend/${{ inputs.target-environment }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Show frontend URL
        run: |
          echo "frontend-url<<${{ steps.pulumi.outputs.bucket_url }}"
          echo "newUI-url<<${{ steps.pulumi.outputs.new_ui_url }}"
