name: Tabiya compass frontend test
on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
    outputs:
      version-info:
        description: 'The frontend version info'
        value: ${{ jobs.build.outputs.version-info }}
jobs:
    poc-lint:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-environment }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Use Node.js 20.x
            uses: actions/setup-node@v4
            with:
              node-version: 20.x
              cache: 'yarn'
              cache-dependency-path: frontend/yarn.lock
          - name: Install node packages
            run: yarn install
            working-directory: frontend
          - name: Lint POC Frontend
            run: yarn run lint
            working-directory: frontend
    test:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-environment }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Use Node.js 20.x
            uses: actions/setup-node@v4
            with:
              node-version: 20.x
              cache: 'yarn'
              cache-dependency-path: frontend-new/yarn.lock
          - name: Install node packages
            run: yarn install
            working-directory: frontend-new
          - name: Lint new Frontend
            run: yarn run lint
            working-directory: frontend-new
          - name: Test new Frontend
            run: yarn run test
            working-directory: frontend-new
          - name: Archive code coverage results
            uses: actions/upload-artifact@v4
            with:
              name: frontend.lcov.info
              path: frontend-new/coverage/lcov.info
              retention-days: 1
    build:
      runs-on: ubuntu-latest
      environment: ${{ inputs.target-environment }}
      outputs:
        version-info: ${{ steps.setNewVersionInfo.outputs.version-info }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Use Node.js 20.x
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'yarn'
            cache-dependency-path: frontend-new/yarn.lock
        - name: Install node packages
          run: yarn install
          working-directory: frontend-new
        - name: Set Version Info for new frontend
          id: setNewVersionInfo
          run: |
            ./pipeline/setVersionInfo.sh frontend-new/public/data/version.json
            cat frontend-new/public/data/version.json
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "version-info<<$EOF" >> "$GITHUB_OUTPUT"
            echo "$(cat ./frontend-new/public/data/version.json)" >> "$GITHUB_OUTPUT"
            echo "$EOF" >> "$GITHUB_OUTPUT"
        - name: Build
          run: yarn build
          working-directory: frontend-new
        - name: Archive build bundle
          uses: actions/upload-artifact@v4
          with:
            name: frontend.build.folder
            path: frontend-new/build/
            retention-days: 1
    accessibility:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Use Node.js 20.x
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            cache: 'yarn'
            cache-dependency-path: frontend-new/yarn.lock
        - name: Cache Playwright browsers
          uses: actions/cache@v4
          with:
            path: ~/.cache/ms-playwright
            key: playwright-browsers-${{ runner.os }}-v1
            restore-keys: playwright-browsers-${{ runner.os }}-
        - name: Install dependencies
          run: yarn install
          working-directory: frontend-new
        - name: Accessibility Tests
          run: |
            npx playwright install --with-deps
            yarn run build-storybook && yarn run test:accessibility
          working-directory: frontend-new
