name: build

on:
  workflow_call:
    inputs:
      target-environment:
        description: 'The target environment to deploy to'
        required: true
        type: string
      frontend-url:
        description: 'The frontend URL'
        required: true
        type: string
      backend-url:
        description: 'The backend URL'
        required: true
        type: string
      taxonomy-database-name:
        description: 'The taxonomy database name'
        required: true
        type: string
      taxonomy-model-id:
        description: 'The taxonomy model ID'
        required: true
        type: string
      application-database-name:
        description: 'The application database name'
        required: true
        type: string
      userdata-database-name:
        description: 'The userdata database name'
        required: true
        type: string
      vertex-api-region:
        description: 'The vertex API region'
        required: true
        type: string
    outputs:
      frontend-version-info:
        value: ${{ jobs.build-frontend.outputs.version-info }}
        description: 'The frontend version info'

jobs:
  # Backend
  test-backend:
    uses: ./.github/workflows/unit-test-backend.yml
    secrets: inherit
    with:
      target-environment: ${{ inputs.target-environment }}
      backend-url: ${{ inputs.backend-url }}
      frontend-url: ${{ inputs.frontend-url }}
      taxonomy-database-name: ${{ inputs.taxonomy-database-name }}
      taxonomy-model-id: ${{ inputs.taxonomy-model-id }}
      application-database-name: ${{ inputs.application-database-name }}
      userdata-database-name: ${{ inputs.userdata-database-name }}
      vertex-api-region: ${{ inputs.vertex-api-region }}

  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    secrets: inherit
    with:
      target-environment: ${{ inputs.target-environment }}
