name: Tabiya Compass Deploy Auth
on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
      frontend-domain:
        required: true
        type: string
    outputs:
      identity_platform_client_api_key:
        description: "The identity platform client api key"
        value: ${{ jobs.deploy.outputs.identity_platform_client_api_key }}
      identity_platform_client_firebase_auth_domain:
        description: "The identity platform client firebase auth domain"
        value: ${{ jobs.deploy.outputs.identity_platform_client_firebase_auth_domain }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    outputs:
      identity_platform_client_api_key: ${{ steps.pulumi.outputs.identity_platform_client_api_key }}
      # currently the auth domain points to the firebase subdomain, in the future it may point to a custom domain e.g. auth.dev.compass.tabiya.tech
      identity_platform_client_firebase_auth_domain: ${{ steps.pulumi.outputs.identity_platform_client_firebase_subdomain }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install python packages
        run: pip install -r requirements.txt
        working-directory: iac
      - name: Setup google-cloud-auth
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      - name: show prospective envs
        run: |
          echo "frontend-domain<<${{ inputs.frontend-domain }}"
      - name: Deploy Auth
        id: pulumi
        uses: pulumi/actions@v5
        with:
          work-dir: iac/auth
          command: up
          stack-name: tabiya-tech/compass-auth/${{ inputs.target-environment }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_OAUTH_CLIENT_ID: ${{ secrets.GCP_OAUTH_CLIENT_ID }}
          GCP_OAUTH_CLIENT_SECRET: ${{ secrets.GCP_OAUTH_CLIENT_SECRET }}
          FRONTEND_DOMAIN: ${{ inputs.frontend-domain }}
