name: Tabiya Compass Deploy AWS NS
on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
      domain-name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Install python packages
        run: pip install -r requirements.txt
        working-directory: iac
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_DNS_UPDATE_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DNS_UPDATE_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-duration-seconds: 1200
          role-session-name: Compass AWS NS
      - name: Deploy AWS NS
        id: pulumi
        uses: pulumi/actions@v5
        with:
          work-dir: iac/aws-ns
          command: up
          stack-name: tabiya-tech/compass-aws-ns/${{ inputs.target-environment }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DOMAIN_NAME: ${{ inputs.domain-name }}