name: Main CI
on: push
  #push:
  # branches:
  #   - main
  #pull_request:
  #  types: [ opened, synchronize, reopened ]

# only one job should run at a time when deploying
concurrency:
  group: ${{github.workflow}}-${{ github.ref_name != 'main' && !contains(github.event.head_commit.message, '[pulumi up]') && github.ref_name || 'deploying' }}
  cancel-in-progress: false


jobs:
  ## Echo the group name to see if the concurrency is working
  #echo-group:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Echo group name
  #      run: echo ${{github.workflow}}-${{ github.ref_name != 'main' && !contains(github.event.head_commit.message, '[pulumi up]') && github.ref_name || 'deploying' }}
  # Setup envs
  setup-env:
    uses: ./.github/workflows/setup-env.yml
    secrets: inherit
    with:
      target-environment: new-dev
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs: [ setup-env]
    with:
      target-environment: new-dev
      frontend-url: ${{ needs.setup-env.outputs.frontend-url }}
      backend-url: ${{ needs.setup-env.outputs.backend-url }}
      taxonomy-database-name: ${{ needs.setup-env.outputs.taxonomy-database-name }}
      taxonomy-model-id: ${{ needs.setup-env.outputs.taxonomy-model-id }}
      application-database-name: ${{ needs.setup-env.outputs.application-database-name }}
      userdata-database-name: ${{ needs.setup-env.outputs.userdata-database-name }}
      vertex-api-region: ${{ needs.setup-env.outputs.vertex-api-region }}

  deploy:
    # This job will only run if the push event is on the main branch or the commit message contains '[pulumi up]'
    # TODO: uncomment this line
    # if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '[pulumi up]'))
    uses: ./.github/workflows/deploy.yml
    needs: [ build, setup-env ]
    secrets: inherit
    with:
      target-environment: new-dev
      domain-name: ${{ needs.setup-env.outputs.domain-name }}
      frontend-url: ${{ needs.setup-env.outputs.frontend-url }}
      frontend-domain: ${{ needs.setup-env.outputs.frontend-domain }}
      backend-url: ${{ needs.setup-env.outputs.backend-url }}
      backend-domain: ${{ needs.setup-env.outputs.backend-domain }}
      taxonomy-database-name: ${{ needs.setup-env.outputs.taxonomy-database-name }}
      taxonomy-model-id: ${{ needs.setup-env.outputs.taxonomy-model-id }}
      application-database-name: ${{ needs.setup-env.outputs.application-database-name }}
      userdata-database-name: ${{ needs.setup-env.outputs.userdata-database-name }}
      vertex-api-region: ${{ needs.setup-env.outputs.vertex-api-region }}
      sensitive-data-encryption-key: ${{ needs.setup-env.outputs.sensitive-data-encryption-key }}
      sensitive-data-encryption-key-id: ${{ needs.setup-env.outputs.sensitive-data-encryption-key-id }}
      frontend-version-info: ${{ needs.build.outputs.frontend-version-info }}
