name: Smoke Test the version of the backend/frontend
on:
  workflow_call:
    inputs:
      component:
        description: Either 'frontend' or 'backend'
        required: true
        type: string
      component-url:
        description: The urlbase of the 'frontend' or 'backend'
        required: true
        type: string
      expected-version-info:
        description: The expected version info. It is a json string, see the version.json file in the backend/app folder
        required: true
        type: string
jobs:
  smoke-test:
    name: ${{ inputs.component }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Load cached Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}
      - id: install-dependencies
        shell: bash
        run: poetry install --no-interaction
        working-directory: backend
      - id: smoke-test
        shell: bash
        run: |
          export EXPECTED_VERSION_INFO='${{ inputs.expected-version-info }}'
          export E2E_BASE_URL=${{ inputs.component-url }}
          poetry run pytest smoke_test/test_version.py
        working-directory: ${{ inputs.component }}
