name: Smoke Test the version of the backend
on:
  workflow_call:
    inputs:
      component:
        description: backend
        required: true
        type: string
      component-url:
        description: The urlbase of the 'backend'
        required: true
        type: string
      expected-version-info:
        description: The expected version info. It is a json string, see the version.json file in the backend/app folder
        required: true
        type: string
      get-version-url:
        description: the url for getting the version information.
        required: true
        type: string
jobs:
  smoke-test:
    name: Smoke tests - backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: poetry-0
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Load cached Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}
      - name: Install dependencies
        shell: bash
        run: |
          poetry lock --no-update --no-interaction
          poetry install --no-interaction
        working-directory: backend
      - name: Run smoke tests
        shell: bash
        run: |
          export EXPECTED_VERSION_INFO='${{ inputs.expected-version-info }}'
          export E2E_BASE_URL=${{ inputs.component-url }}
          export GET_VERSION_URL=${{ inputs.get-version-url }}
          poetry run pytest smoke_test/test_version.py
        working-directory: backend
