name: Tabiya compass frontend test
on:
  workflow_call:
    inputs:
      target-environment:
        required: true
        type: string
jobs:
    lint:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-environment }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Use Node.js 20.x
            uses: actions/setup-node@v4
            with:
              node-version: 20.x
              cache: 'yarn'
              cache-dependency-path: frontend/yarn.lock
          - name: Install node packages
            run: yarn install
            working-directory: frontend
          - name: Lint
            run: yarn run lint
            working-directory: frontend
